configurations = {
    # ----- Baseline -----
    "0.1.1" : { # Art Painting -> Cartoon
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'baseline',
        'experiment_name': '0_1_1',
        'experiment_args': '{}',
        'dataset_args': { 'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'cartoon' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "0.1.2" : { # Art Painting -> Sketch
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'baseline',
        'experiment_name': '0_1_2',
        'experiment_args': '{}',
        'dataset_args': { 'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'sketch' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "0.1.3" : { # Art Painting -> Photo
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'baseline',
        'experiment_name': '0_1_3',
        'experiment_args': '{}',
        'dataset_args': { 'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'photo' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },

    # ----- Random activation maps -----
    # ---- ASH module after last convolutional layer ----
    # --- mask out ratio = 0.1 ---
    "1.1.1" : { # Art Painting -> Cartoon
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '1_1_1',
        'experiment_args': {'module_placement': ['layer4.1.conv2'], 'mask_out_ratio': 0.1},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'cartoon' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "1.1.2" : { # Art Painting -> Sketch
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '1_1_2',
        'experiment_args': {'module_placement': ['layer4.1.conv2'], 'mask_out_ratio': 0.1},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'sketch' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "1.1.3" : { # Art Painting -> Photo
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '1_1_3',
        'experiment_args': {'module_placement': ['layer4.1.conv2'], 'mask_out_ratio': 0.1},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'photo' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    # --- mask out ratio = 0.4 ---
    "2.1.1" : { # Art Painting -> Cartoon
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_1_1',
        'experiment_args': {'module_placement': ['layer4.1.conv2'], 'mask_out_ratio': 0.4},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'cartoon' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.1.2" : { # Art Painting -> Sketch
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_1_2',
        'experiment_args': {'module_placement': ['layer4.1.conv2'], 'mask_out_ratio': 0.4},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'sketch' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.1.3" : { # Art Painting -> Photo
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_1_3',
        'experiment_args': {'module_placement': ['layer4.1.conv2'], 'mask_out_ratio': 0.4},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'photo' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    # --- mask out ratio = 0.55 ---
    "2.1.4" : { # Art Painting -> Cartoon
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_1_4',
        'experiment_args': {'module_placement': ['layer4.1.conv2'], 'mask_out_ratio': 0.55},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'cartoon' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.1.5" : { # Art Painting -> Sketch
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_1_5',
        'experiment_args': {'module_placement': ['layer4.1.conv2'], 'mask_out_ratio': 0.55},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'sketch' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.1.6" : { # Art Painting -> Photo
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_1_6',
        'experiment_args': {'module_placement': ['layer4.1.conv2'], 'mask_out_ratio': 0.55},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'photo' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    # --- mask out ratio = 0.75 ---
    "2.1.7" : { # Art Painting -> Cartoon
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_1_7',
        'experiment_args': {'module_placement': ['layer4.1.conv2'], 'mask_out_ratio': 0.75},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'cartoon' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.1.8" : { # Art Painting -> Sketch
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_1_8',
        'experiment_args': {'module_placement': ['layer4.1.conv2'], 'mask_out_ratio': 0.75},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'sketch' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.1.9" : { # Art Painting -> Photo
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_1_9',
        'experiment_args': {'module_placement': ['layer4.1.conv2'], 'mask_out_ratio': 0.75},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'photo' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },

    # ---- ASH module after each convolutional layer ----
    # --- mask out ratio = 0.1 ---
    "1.2.1" : { # Art Painting -> Cartoon
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '1_2_1',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.0.conv2', 'layer1.1.conv1', 'layer1.1.conv2', 'layer2.0.conv1', 'layer2.0.conv2', 'layer2.1.conv1', 'layer2.1.conv2', 'layer3.0.conv1', 'layer3.0.conv2', 'layer3.1.conv1', 'layer3.1.conv2', 'layer4.0.conv1', 'layer4.0.conv2', 'layer4.1.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.1},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'cartoon' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "1.2.2" : { # Art Painting -> Sketch
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '1_2_2',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.0.conv2', 'layer1.1.conv1', 'layer1.1.conv2', 'layer2.0.conv1', 'layer2.0.conv2', 'layer2.1.conv1', 'layer2.1.conv2', 'layer3.0.conv1', 'layer3.0.conv2', 'layer3.1.conv1', 'layer3.1.conv2', 'layer4.0.conv1', 'layer4.0.conv2', 'layer4.1.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.1},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'sketch' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "1.2.3" : { # Art Painting -> Photo
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '1_2_3',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.0.conv2', 'layer1.1.conv1', 'layer1.1.conv2', 'layer2.0.conv1', 'layer2.0.conv2', 'layer2.1.conv1', 'layer2.1.conv2', 'layer3.0.conv1', 'layer3.0.conv2', 'layer3.1.conv1', 'layer3.1.conv2', 'layer4.0.conv1', 'layer4.0.conv2', 'layer4.1.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.1},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'photo' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    # --- mask out ratio = 0.4 ---
    "2.2.1" : { # Art Painting -> Cartoon
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_2_1',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.0.conv2', 'layer1.1.conv1', 'layer1.1.conv2', 'layer2.0.conv1', 'layer2.0.conv2', 'layer2.1.conv1', 'layer2.1.conv2', 'layer3.0.conv1', 'layer3.0.conv2', 'layer3.1.conv1', 'layer3.1.conv2', 'layer4.0.conv1', 'layer4.0.conv2', 'layer4.1.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.4},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'cartoon' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.2.2" : { # Art Painting -> Sketch
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_2_2',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.0.conv2', 'layer1.1.conv1', 'layer1.1.conv2', 'layer2.0.conv1', 'layer2.0.conv2', 'layer2.1.conv1', 'layer2.1.conv2', 'layer3.0.conv1', 'layer3.0.conv2', 'layer3.1.conv1', 'layer3.1.conv2', 'layer4.0.conv1', 'layer4.0.conv2', 'layer4.1.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.4},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'sketch' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.2.3" : { # Art Painting -> Photo
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_2_3',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.0.conv2', 'layer1.1.conv1', 'layer1.1.conv2', 'layer2.0.conv1', 'layer2.0.conv2', 'layer2.1.conv1', 'layer2.1.conv2', 'layer3.0.conv1', 'layer3.0.conv2', 'layer3.1.conv1', 'layer3.1.conv2', 'layer4.0.conv1', 'layer4.0.conv2', 'layer4.1.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.4},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'photo' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    # --- mask out ratio = 0.55 ---
    "2.2.4" : { # Art Painting -> Cartoon
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_2_4',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.0.conv2', 'layer1.1.conv1', 'layer1.1.conv2', 'layer2.0.conv1', 'layer2.0.conv2', 'layer2.1.conv1', 'layer2.1.conv2', 'layer3.0.conv1', 'layer3.0.conv2', 'layer3.1.conv1', 'layer3.1.conv2', 'layer4.0.conv1', 'layer4.0.conv2', 'layer4.1.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.55},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'cartoon' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.2.5" : { # Art Painting -> Sketch
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_2_5',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.0.conv2', 'layer1.1.conv1', 'layer1.1.conv2', 'layer2.0.conv1', 'layer2.0.conv2', 'layer2.1.conv1', 'layer2.1.conv2', 'layer3.0.conv1', 'layer3.0.conv2', 'layer3.1.conv1', 'layer3.1.conv2', 'layer4.0.conv1', 'layer4.0.conv2', 'layer4.1.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.55},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'sketch' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.2.6" : { # Art Painting -> Photo
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_2_6',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.0.conv2', 'layer1.1.conv1', 'layer1.1.conv2', 'layer2.0.conv1', 'layer2.0.conv2', 'layer2.1.conv1', 'layer2.1.conv2', 'layer3.0.conv1', 'layer3.0.conv2', 'layer3.1.conv1', 'layer3.1.conv2', 'layer4.0.conv1', 'layer4.0.conv2', 'layer4.1.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.55},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'photo' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    # --- mask out ratio = 0.75 ---
    "2.2.7" : { # Art Painting -> Cartoon
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_2_7',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.0.conv2', 'layer1.1.conv1', 'layer1.1.conv2', 'layer2.0.conv1', 'layer2.0.conv2', 'layer2.1.conv1', 'layer2.1.conv2', 'layer3.0.conv1', 'layer3.0.conv2', 'layer3.1.conv1', 'layer3.1.conv2', 'layer4.0.conv1', 'layer4.0.conv2', 'layer4.1.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.75},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'cartoon' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.2.8" : { # Art Painting -> Sketch
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_2_8',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.0.conv2', 'layer1.1.conv1', 'layer1.1.conv2', 'layer2.0.conv1', 'layer2.0.conv2', 'layer2.1.conv1', 'layer2.1.conv2', 'layer3.0.conv1', 'layer3.0.conv2', 'layer3.1.conv1', 'layer3.1.conv2', 'layer4.0.conv1', 'layer4.0.conv2', 'layer4.1.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.75},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'sketch' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.2.9" : { # Art Painting -> Photo
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_2_9',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.0.conv2', 'layer1.1.conv1', 'layer1.1.conv2', 'layer2.0.conv1', 'layer2.0.conv2', 'layer2.1.conv1', 'layer2.1.conv2', 'layer3.0.conv1', 'layer3.0.conv2', 'layer3.1.conv1', 'layer3.1.conv2', 'layer4.0.conv1', 'layer4.0.conv2', 'layer4.1.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.75},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'photo' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },

    # ---- ASH module after every three convolutional layers ----
    # --- mask out ratio = 0.1 ---
    "1.3.1" : { # Art Painting -> Cartoon
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '1_3_1',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.1.conv2', 'layer2.1.conv1', 'layer3.0.conv2', 'layer4.0.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.1},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'cartoon' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "1.3.2" : { # Art Painting -> Sketch
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '1_3_2',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.1.conv2', 'layer2.1.conv1', 'layer3.0.conv2', 'layer4.0.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.1},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'sketch' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "1.3.3" : { # Art Painting -> Photo
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '1_3_3',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.1.conv2', 'layer2.1.conv1', 'layer3.0.conv2', 'layer4.0.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.1},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'photo' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    # --- mask out ratio = 0.4 ---
    "2.3.1" : { # Art Painting -> Cartoon
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_3_1',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.1.conv2', 'layer2.1.conv1', 'layer3.0.conv2', 'layer4.0.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.4},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'cartoon' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.3.2" : { # Art Painting -> Sketch
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_3_2',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.1.conv2', 'layer2.1.conv1', 'layer3.0.conv2', 'layer4.0.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.4},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'sketch' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.3.3" : { # Art Painting -> Photo
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_3_3',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.1.conv2', 'layer2.1.conv1', 'layer3.0.conv2', 'layer4.0.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.4},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'photo' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    # --- mask out ratio = 0.55 ---
    "2.3.4" : { # Art Painting -> Cartoon
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_3_4',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.1.conv2', 'layer2.1.conv1', 'layer3.0.conv2', 'layer4.0.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.55},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'cartoon' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.3.5" : { # Art Painting -> Sketch
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_3_5',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.1.conv2', 'layer2.1.conv1', 'layer3.0.conv2', 'layer4.0.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.55},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'sketch' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.3.6" : { # Art Painting -> Photo
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_3_6',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.1.conv2', 'layer2.1.conv1', 'layer3.0.conv2', 'layer4.0.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.55},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'photo' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    # --- mask out ratio = 0.75 ---
    "2.3.7" : { # Art Painting -> Cartoon
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_3_7',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.1.conv2', 'layer2.1.conv1', 'layer3.0.conv2', 'layer4.0.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.75},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'cartoon' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.3.8" : { # Art Painting -> Sketch
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_3_8',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.1.conv2', 'layer2.1.conv1', 'layer3.0.conv2', 'layer4.0.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.75},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'sketch' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "2.3.9" : { # Art Painting -> Photo
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'random',
        'experiment_name': '2_3_9',
        'experiment_args': {'module_placement': ['layer1.0.conv1', 'layer1.1.conv2', 'layer2.1.conv1', 'layer3.0.conv2', 'layer4.0.conv1', 'layer4.1.conv2'], 'mask_out_ratio': 0.75},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'photo' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },

    # ----- Adapting activation maps across domains -----
    # ---- layer2.1.conv2 ----
    "3.1.1": { # Art Painting -> Cartoon
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'domain_adaptation',
        'experiment_name': '3_1_1',
        'experiment_args': {'module_placement': ['layer2.1.conv2']},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'cartoon' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "3.1.2": { # Art Painting -> Sketch
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'domain_adaptation',
        'experiment_name': '3_1_2',
        'experiment_args': {'module_placement': ['layer2.1.conv2']},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'sketch' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    },
    "3.1.3": { # Art Painting -> Photo
        'seed': 0,
        'test_only': False,
        'cpu': False,
        'experiment': 'domain_adaptation',
        'experiment_name': '3_1_3',
        'experiment_args': {'module_placement': ['layer2.1.conv2']},
        'dataset_args': {'text_root': 'data', 'images_root': 'data/kfold/PACS', 'source_domain': 'art_painting', 'target_domain': 'photo' },
        'batch_size': 128,
        'epochs': 30,
        'num_workers': 5,
        'grad_accum_steps': 1
    }
}